[phases.setup]
nixPkgs = ["python312"]

[phases.build]
cmds = [
  "cd shadow-python && python -m pip install -r requirements.txt"
]

[start]
cmd = "cd shadow-python && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

