[phases.setup]
nixPkgs = ["python312"]

[phases.build]
cmds = [
  "cd shadow-python && python -m venv venv",
  "cd shadow-python && venv/bin/pip install --upgrade pip",
  "cd shadow-python && venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "cd shadow-python && venv/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

